\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={MA679\_HW3\_Jianhao},
            pdfauthor={Jianhaoyan},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{MA679\_HW3\_Jianhao}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Jianhaoyan}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{2/6/2019}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}

\begin{document}
\maketitle

\begin{verbatim}
## Loading required package: ParamHelpers
\end{verbatim}

\begin{verbatim}
## -- Attaching packages ------------------------------------- tidyverse 1.2.1 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.0.0     v purrr   0.2.5
## v tibble  1.4.2     v dplyr   0.7.7
## v tidyr   0.8.1     v stringr 1.3.1
## v readr   1.1.1     v forcats 0.3.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts ---------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{verbatim}
## Loading required package: MASS
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'MASS'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     select
\end{verbatim}

\begin{verbatim}
## Loading required package: Matrix
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'Matrix'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:tidyr':
## 
##     expand
\end{verbatim}

\begin{verbatim}
## Loading required package: lme4
\end{verbatim}

\begin{verbatim}
## 
## arm (Version 1.10-1, built: 2018-4-12)
\end{verbatim}

\begin{verbatim}
## Working directory is /Users/yanjianhao/Desktop/MA679HW/MA671HW
\end{verbatim}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'caret'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:purrr':
## 
##     lift
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:mlr':
## 
##     train
\end{verbatim}

\subsubsection{6.Suppose we collect data for a group of students in a
statistics class with variables X1 = hours studied, X2 = undergrad GPA,
and Y = receive an A. We fit a logistic regression and produce estimated
coefficient, βˆ0 = −6, βˆ1 = 0.05, βˆ2 =
1.}\label{suppose-we-collect-data-for-a-group-of-students-in-a-statistics-class-with-variables-x1-hours-studied-x2-undergrad-gpa-and-y-receive-an-a.-we-fit-a-logistic-regression-and-produce-estimated-coefficient-0-6-1-0.05-2-1.}

\subsubsection{(a) Estimate the probability that a student who studies
for 40 h and has an undergrad GPA of 3.5 gets an A in the
class.}\label{a-estimate-the-probability-that-a-student-who-studies-for-40-h-and-has-an-undergrad-gpa-of-3.5-gets-an-a-in-the-class.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{P =}\StringTok{ }\KeywordTok{invlogit}\NormalTok{(}\OperatorTok{-}\DecValTok{6}\OperatorTok{+}\FloatTok{0.05}\OperatorTok{*}\DecValTok{40}\OperatorTok{+}\DecValTok{1}\OperatorTok{*}\FloatTok{3.5}\NormalTok{)}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"The probability of getting a A is"}\NormalTok{, P))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "The probability of getting a A is 0.377540668798145"
\end{verbatim}

\subsubsection{(b) How many hours would the student in part (a) need to
study to have a 50 \% chance of getting an A in the
class?}\label{b-how-many-hours-would-the-student-in-part-a-need-to-study-to-have-a-50-chance-of-getting-an-a-in-the-class}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Hours=}\StringTok{ }\NormalTok{(}\KeywordTok{logit}\NormalTok{(}\FloatTok{0.5}\NormalTok{)}\OperatorTok{+}\DecValTok{6}\OperatorTok{-}\FloatTok{3.5}\NormalTok{)}\OperatorTok{/}\FloatTok{0.05}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"The student needs to study"}\NormalTok{, Hours, }\StringTok{"everyday."}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "The student needs to study 50 everyday."
\end{verbatim}

\subsubsection{8.Suppose that we take a data set, divide it into
equally-sized training and test sets, and then try out two different
classification procedures. First we use logistic regression and get an
error rate of 20 \% on the training data and 30 \% on the test data.
Next we use 1-nearest neigh- bors (i.e.~K = 1) and get an average error
rate (averaged over both test and training data sets) of 18\%. Based on
these results, which method should we prefer to use for classification
of new observations?
Why?}\label{suppose-that-we-take-a-data-set-divide-it-into-equally-sized-training-and-test-sets-and-then-try-out-two-different-classification-procedures.-first-we-use-logistic-regression-and-get-an-error-rate-of-20-on-the-training-data-and-30-on-the-test-data.-next-we-use-1-nearest-neigh--bors-i.e.k-1-and-get-an-average-error-rate-averaged-over-both-test-and-training-data-sets-of-18.-based-on-these-results-which-method-should-we-prefer-to-use-for-classification-of-new-observations-why}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{###We choose logistic regression. The testing error in KNN is 36% because the K equals 1. Comparing these two eror rates, the logistic regression model seems better than KNN.}
\end{Highlighting}
\end{Shaded}

\subsubsection{9. This problem has to do with
odds.}\label{this-problem-has-to-do-with-odds.}

\subsubsection{(a) On average, what fraction of people with an odds of
0.37 of defaulting on their credit card payment will in fact
default?}\label{a-on-average-what-fraction-of-people-with-an-odds-of-0.37-of-defaulting-on-their-credit-card-payment-will-in-fact-default}

\(odds = p/(1-p)\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1=}\FloatTok{0.27}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"we have on average a fraction of"}\NormalTok{,p1,}\StringTok{"of people defaulting on their credit card payment."}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "we have on average a fraction of 0.27 of people defaulting on their credit card payment."
\end{verbatim}

\subsubsection{(b) Suppose that an individual has a 16\% chance of
defaulting on her credit card payment. What are the odds that she will
de-
fault?}\label{b-suppose-that-an-individual-has-a-16-chance-of-defaulting-on-her-credit-card-payment.-what-are-the-odds-that-she-will-de--fault}

\(odds = p/(1-p)\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2=}\FloatTok{0.16}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\FloatTok{0.16}\NormalTok{)}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"The odds that she will default is then"}\NormalTok{,p2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "The odds that she will default is then 0.19047619047619"
\end{verbatim}

\subsubsection{\texorpdfstring{10. This question should be answered
using the ``Weekly'' data set, which is part of the ``ISLR'' package.
This data is similar in nature to the ``Smarket'' data from this
chapter's lab, except that it contains 1089 weekly returns for 21 years,
from the beginning of 1990 to the end of
2010.}{10. This question should be answered using the Weekly data set, which is part of the ISLR package. This data is similar in nature to the Smarket data from this chapter's lab, except that it contains 1089 weekly returns for 21 years, from the beginning of 1990 to the end of 2010.}}\label{this-question-should-be-answered-using-the-weekly-data-set-which-is-part-of-the-islr-package.-this-data-is-similar-in-nature-to-the-smarket-data-from-this-chapters-lab-except-that-it-contains-1089-weekly-returns-for-21-years-from-the-beginning-of-1990-to-the-end-of-2010.}

\subsubsection{\texorpdfstring{a.Produce some numerical and graphical
summaries of the ``Weekly'' data. Do there appear to be any patterns
?}{a.Produce some numerical and graphical summaries of the Weekly data. Do there appear to be any patterns ?}}\label{a.produce-some-numerical-and-graphical-summaries-of-the-weekly-data.-do-there-appear-to-be-any-patterns}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ISLR)}
\NormalTok{kableExtra}\OperatorTok{::}\KeywordTok{kable}\NormalTok{(}\KeywordTok{summary}\NormalTok{(Weekly))}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|l|l|l|l|l|l|l|l|l}
\hline
  &      Year &      Lag1 &      Lag2 &      Lag3 &      Lag4 &      Lag5 &     Volume &     Today & Direction\\
\hline
 & Min.   :1990 & Min.   :-18.1950 & Min.   :-18.1950 & Min.   :-18.1950 & Min.   :-18.1950 & Min.   :-18.1950 & Min.   :0.08747 & Min.   :-18.1950 & Down:484\\
\hline
 & 1st Qu.:1995 & 1st Qu.: -1.1540 & 1st Qu.: -1.1540 & 1st Qu.: -1.1580 & 1st Qu.: -1.1580 & 1st Qu.: -1.1660 & 1st Qu.:0.33202 & 1st Qu.: -1.1540 & Up  :605\\
\hline
 & Median :2000 & Median :  0.2410 & Median :  0.2410 & Median :  0.2410 & Median :  0.2380 & Median :  0.2340 & Median :1.00268 & Median :  0.2410 & NA\\
\hline
 & Mean   :2000 & Mean   :  0.1506 & Mean   :  0.1511 & Mean   :  0.1472 & Mean   :  0.1458 & Mean   :  0.1399 & Mean   :1.57462 & Mean   :  0.1499 & NA\\
\hline
 & 3rd Qu.:2005 & 3rd Qu.:  1.4050 & 3rd Qu.:  1.4090 & 3rd Qu.:  1.4090 & 3rd Qu.:  1.4090 & 3rd Qu.:  1.4050 & 3rd Qu.:2.05373 & 3rd Qu.:  1.4050 & NA\\
\hline
 & Max.   :2010 & Max.   : 12.0260 & Max.   : 12.0260 & Max.   : 12.0260 & Max.   : 12.0260 & Max.   : 12.0260 & Max.   :9.32821 & Max.   : 12.0260 & NA\\
\hline
\end{tabular}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(Weekly)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1089 obs. of  9 variables:
##  $ Year     : num  1990 1990 1990 1990 1990 1990 1990 1990 1990 1990 ...
##  $ Lag1     : num  0.816 -0.27 -2.576 3.514 0.712 ...
##  $ Lag2     : num  1.572 0.816 -0.27 -2.576 3.514 ...
##  $ Lag3     : num  -3.936 1.572 0.816 -0.27 -2.576 ...
##  $ Lag4     : num  -0.229 -3.936 1.572 0.816 -0.27 ...
##  $ Lag5     : num  -3.484 -0.229 -3.936 1.572 0.816 ...
##  $ Volume   : num  0.155 0.149 0.16 0.162 0.154 ...
##  $ Today    : num  -0.27 -2.576 3.514 0.712 1.178 ...
##  $ Direction: Factor w/ 2 levels "Down","Up": 1 1 2 2 2 1 2 2 2 1 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{kableExtra}\OperatorTok{::}\KeywordTok{kable}\NormalTok{(}\KeywordTok{cor}\NormalTok{(Weekly[,}\OperatorTok{-}\DecValTok{9}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|r|r|r|r|r|r|r|r}
\hline
  & Year & Lag1 & Lag2 & Lag3 & Lag4 & Lag5 & Volume & Today\\
\hline
Year & 1.0000000 & -0.0322893 & -0.0333900 & -0.0300065 & -0.0311279 & -0.0305191 & 0.8419416 & -0.0324599\\
\hline
Lag1 & -0.0322893 & 1.0000000 & -0.0748531 & 0.0586357 & -0.0712739 & -0.0081831 & -0.0649513 & -0.0750318\\
\hline
Lag2 & -0.0333900 & -0.0748531 & 1.0000000 & -0.0757209 & 0.0583815 & -0.0724995 & -0.0855131 & 0.0591667\\
\hline
Lag3 & -0.0300065 & 0.0586357 & -0.0757209 & 1.0000000 & -0.0753959 & 0.0606572 & -0.0692877 & -0.0712436\\
\hline
Lag4 & -0.0311279 & -0.0712739 & 0.0583815 & -0.0753959 & 1.0000000 & -0.0756750 & -0.0610746 & -0.0078259\\
\hline
Lag5 & -0.0305191 & -0.0081831 & -0.0724995 & 0.0606572 & -0.0756750 & 1.0000000 & -0.0585174 & 0.0110127\\
\hline
Volume & 0.8419416 & -0.0649513 & -0.0855131 & -0.0692877 & -0.0610746 & -0.0585174 & 1.0000000 & -0.0330778\\
\hline
Today & -0.0324599 & -0.0750318 & 0.0591667 & -0.0712436 & -0.0078259 & 0.0110127 & -0.0330778 & 1.0000000\\
\hline
\end{tabular}

\subsubsection{We can find the correlations of lag and today are really
small.}\label{we-can-find-the-correlations-of-lag-and-today-are-really-small.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{attach}\NormalTok{(Weekly)}
\KeywordTok{plot}\NormalTok{(Volume)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-8-1.pdf}
\#\#\#The most obvious relationship among all of the variables is
between volume and Year. And from the graph, we can find volume increase
over the time.

\subsubsection{\texorpdfstring{Use the full data set to perform a
logistic regression with ``Direction'' as the response and the five lag
variables plus ``Volume'' as predictors. Use the summary function to
print the results. Do any of the predictors appear to be statistically
significant ? If so, which ones
?}{Use the full data set to perform a logistic regression with Direction as the response and the five lag variables plus Volume as predictors. Use the summary function to print the results. Do any of the predictors appear to be statistically significant ? If so, which ones ?}}\label{use-the-full-data-set-to-perform-a-logistic-regression-with-direction-as-the-response-and-the-five-lag-variables-plus-volume-as-predictors.-use-the-summary-function-to-print-the-results.-do-any-of-the-predictors-appear-to-be-statistically-significant-if-so-which-ones}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model_}\DecValTok{1}\NormalTok{ =}\StringTok{ }\KeywordTok{glm}\NormalTok{(Direction }\OperatorTok{~}\StringTok{ }\NormalTok{Lag1 }\OperatorTok{+}\StringTok{ }\NormalTok{Lag2 }\OperatorTok{+}\StringTok{ }\NormalTok{Lag3 }\OperatorTok{+}\StringTok{ }\NormalTok{Lag4 }\OperatorTok{+}\StringTok{ }\NormalTok{Lag5 }\OperatorTok{+}\StringTok{ }\NormalTok{Volume, }\DataTypeTok{data =}\NormalTok{ Weekly, }\DataTypeTok{family =}\NormalTok{ binomial)}
\KeywordTok{summary}\NormalTok{(model_}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + 
##     Volume, family = binomial, data = Weekly)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6949  -1.2565   0.9913   1.0849   1.4579  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)   
## (Intercept)  0.26686    0.08593   3.106   0.0019 **
## Lag1        -0.04127    0.02641  -1.563   0.1181   
## Lag2         0.05844    0.02686   2.175   0.0296 * 
## Lag3        -0.01606    0.02666  -0.602   0.5469   
## Lag4        -0.02779    0.02646  -1.050   0.2937   
## Lag5        -0.01447    0.02638  -0.549   0.5833   
## Volume      -0.02274    0.03690  -0.616   0.5377   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1496.2  on 1088  degrees of freedom
## Residual deviance: 1486.4  on 1082  degrees of freedom
## AIC: 1500.4
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\subsubsection{Only intercept and lag2 are
significant.}\label{only-intercept-and-lag2-are-significant.}

\subsubsection{(c) Compute the confusion matrix and overall fraction of
correct predictions. Explain what the confusion matrix is telling you
about the types of mistakes made by logistic
regression.}\label{c-compute-the-confusion-matrix-and-overall-fraction-of-correct-predictions.-explain-what-the-confusion-matrix-is-telling-you-about-the-types-of-mistakes-made-by-logistic-regression.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{probs <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(model_}\DecValTok{1}\NormalTok{, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred.glm <-}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\StringTok{"Down"}\NormalTok{, }\KeywordTok{length}\NormalTok{(probs))}
\NormalTok{pred.glm[probs }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{] <-}\StringTok{ "Up"}
\KeywordTok{table}\NormalTok{(pred.glm, Direction)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Direction
## pred.glm Down  Up
##     Down   54  48
##     Up    430 557
\end{verbatim}

\subsubsection{We may conclude that the percentage of correct
predictions on the training data is (54+557)/1089wich is equal to
56.1065197\%. In other words 43.8934803\% is the training error rate,
which is often overly optimistic. We could also say that for weeks when
the market goes up, the model is right 92.0661157\% of the time
(557/(48+557)). For weeks when the market goes down, the model is right
only 11.1570248\% of the time
(54/(54+430)).}\label{we-may-conclude-that-the-percentage-of-correct-predictions-on-the-training-data-is-545571089wich-is-equal-to-56.1065197.-in-other-words-43.8934803-is-the-training-error-rate-which-is-often-overly-optimistic.-we-could-also-say-that-for-weeks-when-the-market-goes-up-the-model-is-right-92.0661157-of-the-time-55748557.-for-weeks-when-the-market-goes-down-the-model-is-right-only-11.1570248-of-the-time-5454430.}

\subsubsection{Now fit the logistic regression model using a training
data period from 1990 to 2008, with Lag2 as the only predictor. Compute
the confusion matrix and the overall fraction of correct predictions for
the held out data (that is, the data from 2009 and
2010).}\label{now-fit-the-logistic-regression-model-using-a-training-data-period-from-1990-to-2008-with-lag2-as-the-only-predictor.-compute-the-confusion-matrix-and-the-overall-fraction-of-correct-predictions-for-the-held-out-data-that-is-the-data-from-2009-and-2010.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{db_train =Weekly[,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{9}\NormalTok{)]}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(Year}\OperatorTok{>=}\DecValTok{1990}\OperatorTok{&}\NormalTok{Year}\OperatorTok{<=}\DecValTok{2008}\NormalTok{)}
\NormalTok{db_test=}\StringTok{ }\NormalTok{Weekly[,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{9}\NormalTok{)]}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(Year}\OperatorTok{>=}\DecValTok{2009}\OperatorTok{&}\NormalTok{Year}\OperatorTok{<=}\DecValTok{2010}\NormalTok{)}
\NormalTok{model_}\DecValTok{2}\NormalTok{<-}\KeywordTok{glm}\NormalTok{(Direction}\OperatorTok{~}\NormalTok{Lag2,}\DataTypeTok{data =}\NormalTok{ db_train, }\DataTypeTok{family =}\NormalTok{ binomial)}

\NormalTok{probs2 <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(model_}\DecValTok{2}\NormalTok{, db_test, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred.glm2 <-}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\StringTok{"Down"}\NormalTok{, }\KeywordTok{length}\NormalTok{(probs2))}
\NormalTok{pred.glm2[probs2 }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{] <-}\StringTok{ "Up"}
\KeywordTok{table}\NormalTok{(pred.glm2, db_test}\OperatorTok{$}\NormalTok{Direction)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          
## pred.glm2 Down Up
##      Down    9  5
##      Up     34 56
\end{verbatim}

\subsubsection{Repeat (d) using LDA.}\label{repeat-d-using-lda.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(MASS)}
\NormalTok{fit.lda <-}\StringTok{ }\KeywordTok{lda}\NormalTok{(Direction }\OperatorTok{~}\StringTok{ }\NormalTok{Lag2, }\DataTypeTok{data =}\NormalTok{ db_train)}
\NormalTok{fit.lda}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## lda(Direction ~ Lag2, data = db_train)
## 
## Prior probabilities of groups:
##      Down        Up 
## 0.4477157 0.5522843 
## 
## Group means:
##             Lag2
## Down -0.03568254
## Up    0.26036581
## 
## Coefficients of linear discriminants:
##            LD1
## Lag2 0.4414162
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.lda <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.lda, db_test)}
\KeywordTok{table}\NormalTok{(pred.lda}\OperatorTok{$}\NormalTok{class, db_test}\OperatorTok{$}\NormalTok{Direction)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       
##        Down Up
##   Down    9  5
##   Up     34 56
\end{verbatim}

\subsubsection{In this case, we may conclude that the percentage of
correct predictions on the test data is 62.5\%. In other words 37.5\% is
the test error rate. We could also say that for weeks when the market
goes up, the model is right 91.8032787\% of the time. For weeks when the
market goes down, the model is right only 20.9302326\% of the time.
These results are very close to those obtained with the logistic
regression model which is not
surpising.}\label{in-this-case-we-may-conclude-that-the-percentage-of-correct-predictions-on-the-test-data-is-62.5.-in-other-words-37.5-is-the-test-error-rate.-we-could-also-say-that-for-weeks-when-the-market-goes-up-the-model-is-right-91.8032787-of-the-time.-for-weeks-when-the-market-goes-down-the-model-is-right-only-20.9302326-of-the-time.-these-results-are-very-close-to-those-obtained-with-the-logistic-regression-model-which-is-not-surpising.}

\subsubsection{(f) Repeat (d) using QDA.}\label{f-repeat-d-using-qda.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.qda <-}\StringTok{ }\KeywordTok{qda}\NormalTok{(Direction}\OperatorTok{~}\NormalTok{Lag2, }\DataTypeTok{data =}\NormalTok{ db_train)}
\NormalTok{fit.qda}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## qda(Direction ~ Lag2, data = db_train)
## 
## Prior probabilities of groups:
##      Down        Up 
## 0.4477157 0.5522843 
## 
## Group means:
##             Lag2
## Down -0.03568254
## Up    0.26036581
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.qda<-}\KeywordTok{predict}\NormalTok{(fit.qda,db_test)}
\KeywordTok{table}\NormalTok{(pred.qda}\OperatorTok{$}\NormalTok{class,db_test}\OperatorTok{$}\NormalTok{Direction)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       
##        Down Up
##   Down    0  0
##   Up     43 61
\end{verbatim}

\subsubsection{\texorpdfstring{n this case, we may conclude that the
percentage of correct predictions on the test data is 58.6538462\%. In
other words 41.3461538\% is the test error rate. We could also say that
for weeks when the market goes up, the model is right 100\% of the time.
For weeks when the market goes down, the model is right only 0\% of the
time. We may note, that QDA achieves a correctness of 58.6538462\% even
though the model chooses ``Up'' the whole time
!}{n this case, we may conclude that the percentage of correct predictions on the test data is 58.6538462\%. In other words 41.3461538\% is the test error rate. We could also say that for weeks when the market goes up, the model is right 100\% of the time. For weeks when the market goes down, the model is right only 0\% of the time. We may note, that QDA achieves a correctness of 58.6538462\% even though the model chooses Up the whole time !}}\label{n-this-case-we-may-conclude-that-the-percentage-of-correct-predictions-on-the-test-data-is-58.6538462.-in-other-words-41.3461538-is-the-test-error-rate.-we-could-also-say-that-for-weeks-when-the-market-goes-up-the-model-is-right-100-of-the-time.-for-weeks-when-the-market-goes-down-the-model-is-right-only-0-of-the-time.-we-may-note-that-qda-achieves-a-correctness-of-58.6538462-even-though-the-model-chooses-up-the-whole-time}

\subsubsection{(g) Repeat (d) using KNN with K =
1.}\label{g-repeat-d-using-knn-with-k-1.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(class)}
\NormalTok{train.x =}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(db_train}\OperatorTok{$}\NormalTok{Lag2)}
\NormalTok{test.x =}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(db_test}\OperatorTok{$}\NormalTok{Lag2)}
\NormalTok{train.direction<-}\KeywordTok{factor}\NormalTok{(db_train}\OperatorTok{$}\NormalTok{Direction)}
\NormalTok{fit.knn =}\StringTok{ }\KeywordTok{knn}\NormalTok{(train.x,test.x,train.direction,}\DataTypeTok{k=}\DecValTok{1}\NormalTok{)}
\KeywordTok{table}\NormalTok{(fit.knn, db_test}\OperatorTok{$}\NormalTok{Direction)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        
## fit.knn Down Up
##    Down   21 30
##    Up     22 31
\end{verbatim}

\subsubsection{In this case, we may conclude that the percentage of
correct predictions on the test data is 50\%. In other words 50\% is the
test error rate. We could also say that for weeks when the market goes
up, the model is right 50.8196721\% of the time. For weeks when the
market goes down, the model is right only 48.8372093\% of the
time.}\label{in-this-case-we-may-conclude-that-the-percentage-of-correct-predictions-on-the-test-data-is-50.-in-other-words-50-is-the-test-error-rate.-we-could-also-say-that-for-weeks-when-the-market-goes-up-the-model-is-right-50.8196721-of-the-time.-for-weeks-when-the-market-goes-down-the-model-is-right-only-48.8372093-of-the-time.}

\subsubsection{(h) Which of these methods appears to provide the best
results onthis
data?}\label{h-which-of-these-methods-appears-to-provide-the-best-results-onthis-data}

\subsubsection{If we compare the test error rates, we see that logistic
regression and LDA have the minimum error rates, followed by QDA and
KNN.}\label{if-we-compare-the-test-error-rates-we-see-that-logistic-regression-and-lda-have-the-minimum-error-rates-followed-by-qda-and-knn.}

\subsubsection{(i) Experiment with different combinations of predictors,
includ- ing possible transformations and interactions, for each of the
methods. Report the variables, method, and associated confu- sion matrix
that appears to provide the best results on the held out data. Note that
you should also experiment with values for K in the KNN
classifier.}\label{i-experiment-with-different-combinations-of-predictors-includ--ing-possible-transformations-and-interactions-for-each-of-the-methods.-report-the-variables-method-and-associated-confu--sion-matrix-that-appears-to-provide-the-best-results-on-the-held-out-data.-note-that-you-should-also-experiment-with-values-for-k-in-the-knn-classifier.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train <-}\StringTok{ }\NormalTok{(Year }\OperatorTok{<}\StringTok{ }\DecValTok{2009}\NormalTok{)}
\NormalTok{Weekly.}\DecValTok{20092010}\NormalTok{ <-}\StringTok{ }\NormalTok{Weekly[}\OperatorTok{!}\NormalTok{train, ]}
\NormalTok{Direction.}\DecValTok{20092010}\NormalTok{ <-}\StringTok{ }\NormalTok{Direction[}\OperatorTok{!}\NormalTok{train]}
\NormalTok{train.X <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(Lag2[train])}
\NormalTok{test.X <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(Lag2[}\OperatorTok{!}\NormalTok{train])}
\NormalTok{train.Direction <-}\StringTok{ }\NormalTok{Direction[train]}
\NormalTok{fit.glm3 <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(Direction }\OperatorTok{~}\StringTok{ }\NormalTok{Lag2}\OperatorTok{:}\NormalTok{Lag1, }\DataTypeTok{data =}\NormalTok{ Weekly, }\DataTypeTok{family =}\NormalTok{ binomial, }\DataTypeTok{subset =}\NormalTok{ train)}
\NormalTok{probs3 <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.glm3, Weekly.}\DecValTok{20092010}\NormalTok{, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred.glm3 <-}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\StringTok{"Down"}\NormalTok{, }\KeywordTok{length}\NormalTok{(probs3))}
\NormalTok{pred.glm3[probs3 }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{] =}\StringTok{ "Up"}
\KeywordTok{table}\NormalTok{(pred.glm3, Direction.}\DecValTok{20092010}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Direction.20092010
## pred.glm3 Down Up
##      Down    1  1
##      Up     42 60
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.glm3 }\OperatorTok{==}\StringTok{ }\NormalTok{Direction.}\DecValTok{20092010}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5865385
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# LDA with Lag2 interaction with Lag1}
\NormalTok{fit.lda2 <-}\StringTok{ }\KeywordTok{lda}\NormalTok{(Direction }\OperatorTok{~}\StringTok{ }\NormalTok{Lag2}\OperatorTok{:}\NormalTok{Lag1, }\DataTypeTok{data =}\NormalTok{ Weekly, }\DataTypeTok{subset =}\NormalTok{ train)}
\NormalTok{pred.lda2 <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.lda2, Weekly.}\DecValTok{20092010}\NormalTok{)}
\KeywordTok{mean}\NormalTok{(pred.lda2}\OperatorTok{$}\NormalTok{class }\OperatorTok{==}\StringTok{ }\NormalTok{Direction.}\DecValTok{20092010}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5769231
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# QDA with sqrt(abs(Lag2))}
\NormalTok{fit.qda2 <-}\StringTok{ }\KeywordTok{qda}\NormalTok{(Direction }\OperatorTok{~}\StringTok{ }\NormalTok{Lag2 }\OperatorTok{+}\StringTok{ }\KeywordTok{sqrt}\NormalTok{(}\KeywordTok{abs}\NormalTok{(Lag2)), }\DataTypeTok{data =}\NormalTok{ Weekly, }\DataTypeTok{subset =}\NormalTok{ train)}
\NormalTok{pred.qda2 <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.qda2, Weekly.}\DecValTok{20092010}\NormalTok{)}
\KeywordTok{table}\NormalTok{(pred.qda2}\OperatorTok{$}\NormalTok{class, Direction.}\DecValTok{20092010}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Direction.20092010
##        Down Up
##   Down   12 13
##   Up     31 48
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.qda2}\OperatorTok{$}\NormalTok{class }\OperatorTok{==}\StringTok{ }\NormalTok{Direction.}\DecValTok{20092010}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5769231
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# KNN k =10}
\NormalTok{pred.knn2 <-}\StringTok{ }\KeywordTok{knn}\NormalTok{(train.X, test.X, train.Direction, }\DataTypeTok{k =} \DecValTok{10}\NormalTok{)}
\KeywordTok{table}\NormalTok{(pred.knn2, Direction.}\DecValTok{20092010}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Direction.20092010
## pred.knn2 Down Up
##      Down   17 19
##      Up     26 42
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.knn2 }\OperatorTok{==}\StringTok{ }\NormalTok{Direction.}\DecValTok{20092010}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5673077
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# KNN k = 100}
\NormalTok{pred.knn3 <-}\StringTok{ }\KeywordTok{knn}\NormalTok{(train.X, test.X, train.Direction, }\DataTypeTok{k =} \DecValTok{100}\NormalTok{)}
\KeywordTok{table}\NormalTok{(pred.knn3, Direction.}\DecValTok{20092010}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Direction.20092010
## pred.knn3 Down Up
##      Down   10 12
##      Up     33 49
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.knn3 }\OperatorTok{==}\StringTok{ }\NormalTok{Direction.}\DecValTok{20092010}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5673077
\end{verbatim}

\subsection{4.11}\label{section}

\subsubsection{\texorpdfstring{In this problem, you will develop a model
to predict whether a given car gets high or low gas mileage based on the
``Auto'' data
set.}{In this problem, you will develop a model to predict whether a given car gets high or low gas mileage based on the Auto data set.}}\label{in-this-problem-you-will-develop-a-model-to-predict-whether-a-given-car-gets-high-or-low-gas-mileage-based-on-the-auto-data-set.}

\subsubsection{\texorpdfstring{Create a binary variable, ``mpg01'', that
contains a 1 if ``mpg'' contains a value above its median, and a 0 if
``mpg'' contains a value below its median. You can compute the median
using the median() function. Note you may find it helpful to use the
data.frame() function to create a single data set containing both
``mpg01'' and the other ``Auto''
variables.}{Create a binary variable, mpg01, that contains a 1 if mpg contains a value above its median, and a 0 if mpg contains a value below its median. You can compute the median using the median() function. Note you may find it helpful to use the data.frame() function to create a single data set containing both mpg01 and the other Auto variables.}}\label{create-a-binary-variable-mpg01-that-contains-a-1-if-mpg-contains-a-value-above-its-median-and-a-0-if-mpg-contains-a-value-below-its-median.-you-can-compute-the-median-using-the-median-function.-note-you-may-find-it-helpful-to-use-the-data.frame-function-to-create-a-single-data-set-containing-both-mpg01-and-the-other-auto-variables.}

\begin{verbatim}
## The following object is masked from package:ggplot2:
## 
##     mpg
\end{verbatim}

\subsubsection{\texorpdfstring{Explore the data graphically in order to
investigate the association between ``mpg01'' and the other features.
Which of the other features seem most likely to be useful in predictiong
``mpg01'' ? Scatterplots and boxplots may be useful tools to answer this
question. Describe your
findings.}{Explore the data graphically in order to investigate the association between mpg01 and the other features. Which of the other features seem most likely to be useful in predictiong mpg01 ? Scatterplots and boxplots may be useful tools to answer this question. Describe your findings.}}\label{explore-the-data-graphically-in-order-to-investigate-the-association-between-mpg01-and-the-other-features.-which-of-the-other-features-seem-most-likely-to-be-useful-in-predictiong-mpg01-scatterplots-and-boxplots-may-be-useful-tools-to-answer-this-question.-describe-your-findings.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(Auto[, }\OperatorTok{-}\DecValTok{9}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                     mpg  cylinders displacement horsepower     weight
## mpg           1.0000000 -0.7776175   -0.8051269 -0.7784268 -0.8322442
## cylinders    -0.7776175  1.0000000    0.9508233  0.8429834  0.8975273
## displacement -0.8051269  0.9508233    1.0000000  0.8972570  0.9329944
## horsepower   -0.7784268  0.8429834    0.8972570  1.0000000  0.8645377
## weight       -0.8322442  0.8975273    0.9329944  0.8645377  1.0000000
## acceleration  0.4233285 -0.5046834   -0.5438005 -0.6891955 -0.4168392
## year          0.5805410 -0.3456474   -0.3698552 -0.4163615 -0.3091199
## origin        0.5652088 -0.5689316   -0.6145351 -0.4551715 -0.5850054
## mpg01         0.8369392 -0.7591939   -0.7534766 -0.6670526 -0.7577566
##              acceleration       year     origin      mpg01
## mpg             0.4233285  0.5805410  0.5652088  0.8369392
## cylinders      -0.5046834 -0.3456474 -0.5689316 -0.7591939
## displacement   -0.5438005 -0.3698552 -0.6145351 -0.7534766
## horsepower     -0.6891955 -0.4163615 -0.4551715 -0.6670526
## weight         -0.4168392 -0.3091199 -0.5850054 -0.7577566
## acceleration    1.0000000  0.2903161  0.2127458  0.3468215
## year            0.2903161  1.0000000  0.1815277  0.4299042
## origin          0.2127458  0.1815277  1.0000000  0.5136984
## mpg01           0.3468215  0.4299042  0.5136984  1.0000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pairs}\NormalTok{(Auto)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-17-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(cylinders }\OperatorTok{~}\StringTok{ }\NormalTok{mpg01, }\DataTypeTok{data =}\NormalTok{ Auto, }\DataTypeTok{main =} \StringTok{"Cylinders vs mpg01"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-17-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(displacement }\OperatorTok{~}\StringTok{ }\NormalTok{mpg01, }\DataTypeTok{data =}\NormalTok{ Auto, }\DataTypeTok{main =} \StringTok{"Displacement vs mpg01"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-17-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(horsepower }\OperatorTok{~}\StringTok{ }\NormalTok{mpg01, }\DataTypeTok{data =}\NormalTok{ Auto, }\DataTypeTok{main =} \StringTok{"Horsepower vs mpg01"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-17-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(weight }\OperatorTok{~}\StringTok{ }\NormalTok{mpg01, }\DataTypeTok{data =}\NormalTok{ Auto, }\DataTypeTok{main =} \StringTok{"Weight vs mpg01"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-17-5.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(acceleration }\OperatorTok{~}\StringTok{ }\NormalTok{mpg01, }\DataTypeTok{data =}\NormalTok{ Auto, }\DataTypeTok{main =} \StringTok{"Acceleration vs mpg01"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-17-6.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(year }\OperatorTok{~}\StringTok{ }\NormalTok{mpg01, }\DataTypeTok{data =}\NormalTok{ Auto, }\DataTypeTok{main =} \StringTok{"Year vs mpg01"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-17-7.pdf}
\#\#\#We may conclude that there exists some association between
``mpg01'' and ``cylinders'', ``weight'', ``displacement'' and
``horsepower''.

\subsubsection{Split the data into a training set and a test
set.}\label{split-the-data-into-a-training-set-and-a-test-set.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train <-}\StringTok{ }\NormalTok{(year }\OperatorTok{%%}\StringTok{ }\DecValTok{2} \OperatorTok{==}\StringTok{ }\DecValTok{0}\NormalTok{)}
\NormalTok{Auto.train <-}\StringTok{ }\NormalTok{Auto[train, ]}
\NormalTok{Auto.test <-}\StringTok{ }\NormalTok{Auto[}\OperatorTok{!}\NormalTok{train, ]}
\NormalTok{mpg01.test <-}\StringTok{ }\NormalTok{mpg01[}\OperatorTok{!}\NormalTok{train]}
\end{Highlighting}
\end{Shaded}

\subsubsection{\texorpdfstring{Perform LDA on the training data in order
to predict ``mpg01'' using the variables that seemed most associated
with ``mpg01'' in (b). What is the test error of the model obtained
?}{Perform LDA on the training data in order to predict mpg01 using the variables that seemed most associated with mpg01 in (b). What is the test error of the model obtained ?}}\label{perform-lda-on-the-training-data-in-order-to-predict-mpg01-using-the-variables-that-seemed-most-associated-with-mpg01-in-b.-what-is-the-test-error-of-the-model-obtained}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.lda <-}\StringTok{ }\KeywordTok{lda}\NormalTok{(mpg01 }\OperatorTok{~}\StringTok{ }\NormalTok{cylinders }\OperatorTok{+}\StringTok{ }\NormalTok{weight }\OperatorTok{+}\StringTok{ }\NormalTok{displacement }\OperatorTok{+}\StringTok{ }\NormalTok{horsepower, }\DataTypeTok{data =}\NormalTok{ Auto, }\DataTypeTok{subset =}\NormalTok{ train)}
\NormalTok{fit.lda}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## lda(mpg01 ~ cylinders + weight + displacement + horsepower, data = Auto, 
##     subset = train)
## 
## Prior probabilities of groups:
##         0         1 
## 0.4571429 0.5428571 
## 
## Group means:
##   cylinders   weight displacement horsepower
## 0  6.812500 3604.823     271.7396  133.14583
## 1  4.070175 2314.763     111.6623   77.92105
## 
## Coefficients of linear discriminants:
##                        LD1
## cylinders    -0.6741402638
## weight       -0.0011465750
## displacement  0.0004481325
## horsepower    0.0059035377
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.lda <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.lda, Auto.test)}
\KeywordTok{table}\NormalTok{(pred.lda}\OperatorTok{$}\NormalTok{class, mpg01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    mpg01.test
##      0  1
##   0 86  9
##   1 14 73
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.lda}\OperatorTok{$}\NormalTok{class }\OperatorTok{!=}\StringTok{ }\NormalTok{mpg01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1263736
\end{verbatim}

\subsubsection{\texorpdfstring{Perform QDA on the training data in order
to predict ``mpg01'' using the variables that seemed most associated
with ``mpg01'' in (b). What is the test error of the model obtained
?}{Perform QDA on the training data in order to predict mpg01 using the variables that seemed most associated with mpg01 in (b). What is the test error of the model obtained ?}}\label{perform-qda-on-the-training-data-in-order-to-predict-mpg01-using-the-variables-that-seemed-most-associated-with-mpg01-in-b.-what-is-the-test-error-of-the-model-obtained}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.qda <-}\StringTok{ }\KeywordTok{qda}\NormalTok{(mpg01 }\OperatorTok{~}\StringTok{ }\NormalTok{cylinders }\OperatorTok{+}\StringTok{ }\NormalTok{weight }\OperatorTok{+}\StringTok{ }\NormalTok{displacement }\OperatorTok{+}\StringTok{ }\NormalTok{horsepower, }\DataTypeTok{data =}\NormalTok{ Auto, }\DataTypeTok{subset =}\NormalTok{ train)}
\NormalTok{fit.qda}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## qda(mpg01 ~ cylinders + weight + displacement + horsepower, data = Auto, 
##     subset = train)
## 
## Prior probabilities of groups:
##         0         1 
## 0.4571429 0.5428571 
## 
## Group means:
##   cylinders   weight displacement horsepower
## 0  6.812500 3604.823     271.7396  133.14583
## 1  4.070175 2314.763     111.6623   77.92105
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.qda}\OperatorTok{$}\NormalTok{class }\OperatorTok{!=}\StringTok{ }\NormalTok{mpg01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in `!=.default`(pred.qda$class, mpg01.test): longer object length
## is not a multiple of shorter object length
\end{verbatim}

\begin{verbatim}
## Warning in is.na(e1) | is.na(e2): longer object length is not a multiple of
## shorter object length
\end{verbatim}

\begin{verbatim}
## [1] 1
\end{verbatim}

\subsubsection{\texorpdfstring{Perform logistic regression on the
training data in order to predict ``mpg01'' using the variables that
seemed most associated with ``mpg01'' in (b). What is the test error of
the model obtained
?}{Perform logistic regression on the training data in order to predict mpg01 using the variables that seemed most associated with mpg01 in (b). What is the test error of the model obtained ?}}\label{perform-logistic-regression-on-the-training-data-in-order-to-predict-mpg01-using-the-variables-that-seemed-most-associated-with-mpg01-in-b.-what-is-the-test-error-of-the-model-obtained}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.glm <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(mpg01 }\OperatorTok{~}\StringTok{ }\NormalTok{cylinders }\OperatorTok{+}\StringTok{ }\NormalTok{weight }\OperatorTok{+}\StringTok{ }\NormalTok{displacement }\OperatorTok{+}\StringTok{ }\NormalTok{horsepower, }\DataTypeTok{data =}\NormalTok{ Auto, }\DataTypeTok{family =}\NormalTok{ binomial, }\DataTypeTok{subset =}\NormalTok{ train)}
\KeywordTok{summary}\NormalTok{(fit.glm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = mpg01 ~ cylinders + weight + displacement + horsepower, 
##     family = binomial, data = Auto, subset = train)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.48027  -0.03413   0.10583   0.29634   2.57584  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  17.658730   3.409012   5.180 2.22e-07 ***
## cylinders    -1.028032   0.653607  -1.573   0.1158    
## weight       -0.002922   0.001137  -2.569   0.0102 *  
## displacement  0.002462   0.015030   0.164   0.8699    
## horsepower   -0.050611   0.025209  -2.008   0.0447 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 289.58  on 209  degrees of freedom
## Residual deviance:  83.24  on 205  degrees of freedom
## AIC: 93.24
## 
## Number of Fisher Scoring iterations: 7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{probs <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.glm, Auto.test, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred.glm <-}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\KeywordTok{length}\NormalTok{(probs))}
\NormalTok{pred.glm[probs }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{] <-}\StringTok{ }\DecValTok{1}
\KeywordTok{table}\NormalTok{(pred.glm, mpg01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         mpg01.test
## pred.glm  0  1
##        0 89 11
##        1 11 71
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.glm }\OperatorTok{!=}\StringTok{ }\NormalTok{mpg01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1208791
\end{verbatim}

\subsubsection{Perform KNN on the training data, with several values of
K}\label{perform-knn-on-the-training-data-with-several-values-of-k}

, in order to predict ``mpg01'' using the variables that seemed most
associated with ``mpg01'' in (b). What test errors do you obtain ? Which
value of K seems to perform the best on this data set ?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train.X <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(cylinders, weight, displacement, horsepower)[train, ]}
\NormalTok{test.X <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(cylinders, weight, displacement, horsepower)[}\OperatorTok{!}\NormalTok{train, ]}
\NormalTok{train.mpg01 <-}\StringTok{ }\NormalTok{mpg01[train]}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{pred.knn <-}\StringTok{ }\KeywordTok{knn}\NormalTok{(train.X, test.X, train.mpg01, }\DataTypeTok{k =} \DecValTok{1}\NormalTok{)}
\KeywordTok{table}\NormalTok{(pred.knn, mpg01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         mpg01.test
## pred.knn  0  1
##        0 83 11
##        1 17 71
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.knn }\OperatorTok{!=}\StringTok{ }\NormalTok{mpg01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1538462
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.knn <-}\StringTok{ }\KeywordTok{knn}\NormalTok{(train.X, test.X, train.mpg01, }\DataTypeTok{k =} \DecValTok{10}\NormalTok{)}
\KeywordTok{table}\NormalTok{(pred.knn, mpg01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         mpg01.test
## pred.knn  0  1
##        0 77  7
##        1 23 75
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.knn }\OperatorTok{!=}\StringTok{ }\NormalTok{mpg01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1648352
\end{verbatim}

\subsection{4.12}\label{section-1}

\subsubsection{Write a function, Power(), that prints out the result of
raising 2 to the 3rd power. In other words, your function should compute
23and print out the
results.}\label{write-a-function-power-that-prints-out-the-result-of-raising-2-to-the-3rd-power.-in-other-words-your-function-should-compute-23and-print-out-the-results.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Power <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{() \{}
    \DecValTok{2}\OperatorTok{^}\DecValTok{3}
\NormalTok{\}}

\KeywordTok{Power}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8
\end{verbatim}

\subsubsection{\texorpdfstring{Create a new function, Power2(), that
allows you to pass any two numbers, ``x'' and ``a'', and prints out the
value of
``x\^{}a''.}{Create a new function, Power2(), that allows you to pass any two numbers, x and a, and prints out the value of x\^{}a.}}\label{create-a-new-function-power2-that-allows-you-to-pass-any-two-numbers-x-and-a-and-prints-out-the-value-of-xa.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Power2 <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x,a)\{}
\NormalTok{  x}\OperatorTok{^}\NormalTok{a}
\NormalTok{\}}
\KeywordTok{Power2}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8
\end{verbatim}

\subsubsection{Using the Power2() function that you just wrote, compute
103, 817, and
1313.}\label{using-the-power2-function-that-you-just-wrote-compute-103-817-and-1313.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{Power2}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{Power2}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DecValTok{17}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.2518e+15
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{Power2}\NormalTok{(}\DecValTok{131}\NormalTok{, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2248091
\end{verbatim}

\subsubsection{\texorpdfstring{Now create a new function, Power3(), that
actually returns the result ``x\^{}a'' as an R object, rather than
simply printing it to the screen. That is, if you store the value
``x\^{}a'' in an object called ``result'' within your function, then you
can simply return() this
result.}{Now create a new function, Power3(), that actually returns the result x\^{}a as an R object, rather than simply printing it to the screen. That is, if you store the value x\^{}a in an object called result within your function, then you can simply return() this result.}}\label{now-create-a-new-function-power3-that-actually-returns-the-result-xa-as-an-r-object-rather-than-simply-printing-it-to-the-screen.-that-is-if-you-store-the-value-xa-in-an-object-called-result-within-your-function-then-you-can-simply-return-this-result.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Power3 <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x , a) \{}
\NormalTok{    result <-}\StringTok{ }\NormalTok{x}\OperatorTok{^}\NormalTok{a}
    \KeywordTok{return}\NormalTok{(result)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\subsubsection{Now using the Power3() function, create a plot of
f(x)=x3. The x-axis should display a range of integers from 1 to 10, and
the y-axis should display x2. Label the axes appropriately, and use an
appropriate title for the figure. Consider displaying either teh x-axis,
the y-axis, or both on the
log-scale.}\label{now-using-the-power3-function-create-a-plot-of-fxx3.-the-x-axis-should-display-a-range-of-integers-from-1-to-10-and-the-y-axis-should-display-x2.-label-the-axes-appropriately-and-use-an-appropriate-title-for-the-figure.-consider-displaying-either-teh-x-axis-the-y-axis-or-both-on-the-log-scale.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x <-}\StringTok{ }\DecValTok{1}\OperatorTok{:}\DecValTok{10}
\KeywordTok{plot}\NormalTok{(x, }\KeywordTok{Power3}\NormalTok{(x, }\DecValTok{2}\NormalTok{), }\DataTypeTok{log =} \StringTok{"xy"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"Log of x"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"Log of x^2"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Log of x^2 vs Log of x"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-27-1.pdf}

\subsubsection{\texorpdfstring{Create a function, PlotPower(), that
allows you to create a plot of ``x'' against ``x\^{}a'' for a fixed
``a'' and for a range of values of
``x''.}{Create a function, PlotPower(), that allows you to create a plot of x against x\^{}a for a fixed a and for a range of values of x.}}\label{create-a-function-plotpower-that-allows-you-to-create-a-plot-of-x-against-xa-for-a-fixed-a-and-for-a-range-of-values-of-x.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PlotPower <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(x, a) \{}
    \KeywordTok{plot}\NormalTok{(x, }\KeywordTok{Power3}\NormalTok{(x, a))}
\NormalTok{\}}

\KeywordTok{PlotPower}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MA679_HW3_JIANHAO_files/figure-latex/unnamed-chunk-28-1.pdf}

\subsection{13}\label{section-2}

\subsubsection{\texorpdfstring{Using the ``Boston'' data set, fit
classification models in order to predict whether a given suburb has a
crime rate above or below the median. Explore the logistic regression,
LDA, and KNN models using various subsets of the predictors. Describe
your
findings.}{Using the Boston data set, fit classification models in order to predict whether a given suburb has a crime rate above or below the median. Explore the logistic regression, LDA, and KNN models using various subsets of the predictors. Describe your findings.}}\label{using-the-boston-data-set-fit-classification-models-in-order-to-predict-whether-a-given-suburb-has-a-crime-rate-above-or-below-the-median.-explore-the-logistic-regression-lda-and-knn-models-using-various-subsets-of-the-predictors.-describe-your-findings.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(MASS)}
\KeywordTok{attach}\NormalTok{(Boston)}
\NormalTok{crim01 <-}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\KeywordTok{length}\NormalTok{(crim))}
\NormalTok{crim01[crim }\OperatorTok{>}\StringTok{ }\KeywordTok{median}\NormalTok{(crim)] <-}\StringTok{ }\DecValTok{1}
\NormalTok{Boston <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(Boston, crim01)}

\NormalTok{train <-}\StringTok{ }\DecValTok{1}\OperatorTok{:}\NormalTok{(}\KeywordTok{length}\NormalTok{(crim) }\OperatorTok{/}\StringTok{ }\DecValTok{2}\NormalTok{)}
\NormalTok{test <-}\StringTok{ }\NormalTok{(}\KeywordTok{length}\NormalTok{(crim) }\OperatorTok{/}\StringTok{ }\DecValTok{2} \OperatorTok{+}\StringTok{ }\DecValTok{1}\NormalTok{)}\OperatorTok{:}\KeywordTok{length}\NormalTok{(crim)}
\NormalTok{Boston.train <-}\StringTok{ }\NormalTok{Boston[train, ]}
\NormalTok{Boston.test <-}\StringTok{ }\NormalTok{Boston[test, ]}
\NormalTok{crim01.test <-}\StringTok{ }\NormalTok{crim01[test]}
\NormalTok{fit.glm <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(crim01 }\OperatorTok{~}\StringTok{ }\NormalTok{. }\OperatorTok{-}\StringTok{ }\NormalTok{crim01 }\OperatorTok{-}\StringTok{ }\NormalTok{crim, }\DataTypeTok{data =}\NormalTok{ Boston, }\DataTypeTok{family =}\NormalTok{ binomial, }\DataTypeTok{subset =}\NormalTok{ train)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{probs <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.glm, Boston.test, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred.glm <-}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\KeywordTok{length}\NormalTok{(probs))}
\NormalTok{pred.glm[probs }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{] <-}\StringTok{ }\DecValTok{1}
\KeywordTok{table}\NormalTok{(pred.glm, crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         crim01.test
## pred.glm   0   1
##        0  68  24
##        1  22 139
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.glm }\OperatorTok{!=}\StringTok{ }\NormalTok{crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1818182
\end{verbatim}

\subsubsection{We may conclude that, for this logistic regression, we
have a test error rate of
18.1818182\%.}\label{we-may-conclude-that-for-this-logistic-regression-we-have-a-test-error-rate-of-18.1818182.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.glm <-}\StringTok{ }\KeywordTok{glm}\NormalTok{(crim01 }\OperatorTok{~}\StringTok{ }\NormalTok{. }\OperatorTok{-}\StringTok{ }\NormalTok{crim01 }\OperatorTok{-}\StringTok{ }\NormalTok{crim }\OperatorTok{-}\StringTok{ }\NormalTok{chas }\OperatorTok{-}\StringTok{ }\NormalTok{nox, }\DataTypeTok{data =}\NormalTok{ Boston,}\DataTypeTok{family =}\NormalTok{ binomial, }\DataTypeTok{subset =}\NormalTok{ train)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{probs <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.glm, Boston.test, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{pred.glm <-}\StringTok{ }\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\KeywordTok{length}\NormalTok{(probs))}
\NormalTok{pred.glm[probs }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{] <-}\StringTok{ }\DecValTok{1}
\KeywordTok{table}\NormalTok{(pred.glm, crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         crim01.test
## pred.glm   0   1
##        0  78  28
##        1  12 135
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.glm }\OperatorTok{!=}\StringTok{ }\NormalTok{crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1581028
\end{verbatim}

\subsubsection{We may conclude that, for this logistic regression, we
have a test error rate of
15.8102767\%.}\label{we-may-conclude-that-for-this-logistic-regression-we-have-a-test-error-rate-of-15.8102767.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.lda <-}\StringTok{ }\KeywordTok{lda}\NormalTok{(crim01 }\OperatorTok{~}\StringTok{ }\NormalTok{. }\OperatorTok{-}\StringTok{ }\NormalTok{crim01 }\OperatorTok{-}\StringTok{ }\NormalTok{crim, }\DataTypeTok{data =}\NormalTok{ Boston, }\DataTypeTok{subset =}\NormalTok{ train)}
\NormalTok{pred.lda <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.lda, Boston.test)}
\KeywordTok{table}\NormalTok{(pred.lda}\OperatorTok{$}\NormalTok{class, crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    crim01.test
##       0   1
##   0  80  24
##   1  10 139
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.lda}\OperatorTok{$}\NormalTok{class }\OperatorTok{!=}\StringTok{ }\NormalTok{crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1343874
\end{verbatim}

\subsubsection{We may conclude that, for this LDA, we have a test error
rate of
13.4387352\%.}\label{we-may-conclude-that-for-this-lda-we-have-a-test-error-rate-of-13.4387352.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit.lda <-}\StringTok{ }\KeywordTok{lda}\NormalTok{(crim01 }\OperatorTok{~}\StringTok{ }\NormalTok{. }\OperatorTok{-}\StringTok{ }\NormalTok{crim01 }\OperatorTok{-}\StringTok{ }\NormalTok{crim }\OperatorTok{-}\StringTok{ }\NormalTok{chas }\OperatorTok{-}\StringTok{ }\NormalTok{nox, }\DataTypeTok{data =}\NormalTok{ Boston, }\DataTypeTok{subset =}\NormalTok{ train)}
\NormalTok{pred.lda <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(fit.lda, Boston.test)}
\KeywordTok{table}\NormalTok{(pred.lda}\OperatorTok{$}\NormalTok{class, crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    crim01.test
##       0   1
##   0  82  30
##   1   8 133
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.lda}\OperatorTok{$}\NormalTok{class }\OperatorTok{!=}\StringTok{ }\NormalTok{crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1501976
\end{verbatim}

\subsubsection{We may conclude that, for this LDA, we have a test error
rate of
15.0197628\%.}\label{we-may-conclude-that-for-this-lda-we-have-a-test-error-rate-of-15.0197628.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train.X <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(zn, indus, chas, nox, rm, age, dis, rad, tax, ptratio, black, lstat, medv)[train, ]}
\NormalTok{test.X <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(zn, indus, chas, nox, rm, age, dis, rad, tax, ptratio, black, lstat, medv)[test, ]}
\NormalTok{train.crim01 <-}\StringTok{ }\NormalTok{crim01[train]}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{pred.knn <-}\StringTok{ }\KeywordTok{knn}\NormalTok{(train.X, test.X, train.crim01, }\DataTypeTok{k =} \DecValTok{1}\NormalTok{)}
\KeywordTok{table}\NormalTok{(pred.knn, crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         crim01.test
## pred.knn   0   1
##        0  85 111
##        1   5  52
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.knn }\OperatorTok{!=}\StringTok{ }\NormalTok{crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.458498
\end{verbatim}

\subsubsection{We may conclude that, for this KNN (k=1), we have a test
error rate of
45.8498024\%.}\label{we-may-conclude-that-for-this-knn-k1-we-have-a-test-error-rate-of-45.8498024.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.knn <-}\StringTok{ }\KeywordTok{knn}\NormalTok{(train.X, test.X, train.crim01, }\DataTypeTok{k =} \DecValTok{10}\NormalTok{)}
\KeywordTok{table}\NormalTok{(pred.knn, crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         crim01.test
## pred.knn   0   1
##        0  83  23
##        1   7 140
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(pred.knn }\OperatorTok{!=}\StringTok{ }\NormalTok{crim01.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1185771
\end{verbatim}


\end{document}
